//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessScenarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapacityRequirement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CapacityRequirement()
        {
            this.RoomBookings = new HashSet<RoomBooking>();
        }
    
        public System.Guid OID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> RoomSetup { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.Guid> Event { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
    
        public virtual Event Event1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomBooking> RoomBookings { get; set; }
    }
}
