//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessScenarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomCapacity
    {
        public System.Guid OID { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> Setup { get; set; }
        public Nullable<System.Guid> Room { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
    
        public virtual Room Room1 { get; set; }
    }
}
